import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactRedux from "@/components/wrapper/reactRedux";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashoard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactRedux>{children}</ReactRedux>
      </body>
    </html>
  );
}
